version: "3"

services:
  kafka-1:
    build:
      context: ./kafka-1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    ports:
      - "9091:9092"
    volumes:
      - kafka-1-data:/kafka/data

  kafka-2:
    build:
      context: ./kafka-2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    ports:
      - "9092:9092"
    volumes:
      - kafka-2-data:/kafka/data

  kafka-3:
    build:
      context: ./kafka-3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
    ports:
      - "9093:9092"
    volumes:
      - kafka-3-data:/kafka/data

  zookeeper:
    image: zookeeper:3.4
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/data

  image-uploader:
    build:
      context: ./imageUploader
    environment:
      S3_REGION: "your_s3_region"
      S3_BUCKET: "your_s3_bucket"
      KAFKA_TOPIC: "your_kafka_topic"
      KAFKA_BROKERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8080:8080"

  image-resizer:
    build:
      context: ./imageResizer
    environment:
      S3_REGION: "your_s3_region"
      S3_BUCKET: "your_s3_bucket"
      KAFKA_TOPIC: "your_kafka_topic"
      KAFKA_BROKERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  nginx:
    build:
      context: ./nginx
    depends_on:
      - image-uploader
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-log:/var/log/nginx
    networks:
      - nginx_network

volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
  zookeeper-data:
  nginx-log:

networks:
  nginx_network: